import type { NextFunction, Request, Response } from "express";
import mongoose from "mongoose";
import { z } from "zod";
import { Battle } from "../models/battle.model.js";
import { User } from "../models/user.model.js";
import { ApiError } from "../utils/apiError.js";
import { DIFFICULTIES, generateRoomCode } from "../utils/constants.js";

const createSchema = z.object({ difficulty: z.enum(DIFFICULTIES).default("easy"), language: z.string().max(40).nullable().default(null), timeLimit: z.number().int().min(30).max(600).default(60) });
const joinSchema = z.object({ roomCode: z.string().trim().toUpperCase().regex(/^[A-Z0-9]{6}$/) });
const answerSchema = z.object({ questionId: z.string().min(1), answer: z.string().max(200), timeTaken: z.number().min(0).max(600) });
function questions(language: string | null, difficulty: "easy" | "medium" | "hard") { const lang = language || "JavaScript"; return [{ questionId: "event-loop", prompt: "What does this code log?", type: "code_output", language: lang, options: ["A, B, C", "A, C, B", "B, A, C", "C, B, A"], correctAnswer: "A, C, B", explanation: "Promise callbacks run in the microtask queue after synchronous statements.", code: "console.log('A')\nPromise.resolve().then(() => console.log('B'))\nconsole.log('C')", tags: ["async", "fundamentals"], xpValue: difficulty === "hard" ? 50 : difficulty === "medium" ? 35 : 25 }, { questionId: "array-method", prompt: "Which array method returns a new array after transforming each item?", type: "mcq", language: lang, options: ["forEach", "map", "find", "some"], correctAnswer: "map", explanation: "map transforms every element and returns the resulting array.", code: null, tags: ["arrays"], xpValue: 25 }, { questionId: "strict-equality", prompt: "Which operator compares both value and type in JavaScript?", type: "mcq", language: lang, options: ["==", "===", "=", "!="], correctAnswer: "===", explanation: "Strict equality does not coerce types.", code: null, tags: ["operators"], xpValue: 25 }]; }
async function uniqueCode() { for (let attempt = 0; attempt < 8; attempt += 1) { const roomCode = generateRoomCode(); if (!await Battle.exists({ roomCode })) return roomCode; } throw ApiError.internal("Unable to allocate a room code. Please try again."); }
function hasPlayer(battle: { players: Array<{ userId: { equals(id: unknown): boolean } }> }, id: unknown) { return battle.players.some((player) => player.userId.equals(id)); }
async function stateFor(battle: any, userId: unknown) { const users = await User.find({ _id: { $in: battle.players.map((player: any) => player.userId) } }); const mine = battle.players.find((player: any) => player.userId.equals(userId)); return { battleId: battle.id, roomCode: battle.roomCode, status: battle.status, mode: "1v1", difficulty: battle.difficulty, language: battle.language, timeLimit: battle.timeLimit, currentQuestionIndex: mine?.answers.length ?? 0, totalQuestions: battle.questions.length, players: battle.players.map((player: any) => { const user = users.find((candidate) => candidate._id.equals(player.userId)); return { userId: player.userId.toString(), username: user?.userName ?? "Developer", avatarUrl: user?.avatarUrl ?? null, score: player.score, isHost: player.userId.equals(battle.hostId) }; }), questions: battle.status === "active" ? battle.questions.map(({ correctAnswer, explanation, ...question }: any) => question) : [], myAnswer: mine?.answers.at(-1)?.answer ?? null, result: battle.status === "finished" ? resultFor(battle, userId) : null, startedAt: battle.startedAt?.toISOString() ?? null }; }
function resultFor(battle: any, userId: unknown) { const mine = battle.players.find((player: any) => player.userId.equals(userId)); const other = battle.players.find((player: any) => !player.userId.equals(userId)); const accuracy = (player: any) => player.answers.length ? Math.round(player.answers.filter((answer: any) => answer.isCorrect).length / player.answers.length * 100) : 0; return { winner: battle.winnerId?.toString() ?? null, isDraw: !battle.winnerId, myScore: mine?.score ?? 0, opponentScore: other?.score ?? 0, myAccuracy: accuracy(mine), opponentAccuracy: accuracy(other), xpEarned: 0, badgesEarned: [], myAnswers: mine?.answers ?? [], opponentAnswers: other?.answers ?? [], endedAt: battle.endedAt?.toISOString() ?? new Date().toISOString() }; }
export async function createBattle(req: Request, res: Response, next: NextFunction) { try { const input = createSchema.parse(req.body); const roomCode = await uniqueCode(); const userId = new mongoose.Types.ObjectId(req.user!.id); const battle = await Battle.create({ roomCode, hostId: userId, players: [{ userId }], difficulty: input.difficulty, language: input.language, timeLimit: input.timeLimit, questions: questions(input.language, input.difficulty) }); return res.success(201, "Battle room created", { roomCode, battleId: battle.id }); } catch (error) { next(error); } }
export async function joinBattle(req: Request, res: Response, next: NextFunction) { try { const { roomCode } = joinSchema.parse(req.body); const battle = await Battle.findOne({ roomCode }); if (!battle) throw ApiError.notFound("Room not found"); if (battle.status !== "waiting") throw ApiError.badRequest("This battle has already started"); if (!hasPlayer(battle, req.user!.id)) { if (battle.players.length >= 2) throw ApiError.badRequest("This room is full"); battle.players.push({ userId: new mongoose.Types.ObjectId(req.user!.id), score: 0, answers: [] }); await battle.save(); } return res.success(200, "Joined battle room", { roomCode: battle.roomCode, battleId: battle.id }); } catch (error) { next(error); } }
export async function getRoom(req: Request, res: Response, next: NextFunction) { try { const battle = await Battle.findOne({ roomCode: String(req.params.roomCode).toUpperCase() }); if (!battle || !hasPlayer(battle, req.user!.id)) throw ApiError.notFound("Battle room not found"); return res.success(200, "Battle room", await stateFor(battle, req.user!.id)); } catch (error) { next(error); } }
export async function startBattle(req: Request, res: Response, next: NextFunction) { try { const battle = await Battle.findOne({ roomCode: String(req.params.roomCode).toUpperCase() }); if (!battle || !hasPlayer(battle, req.user!.id)) throw ApiError.notFound("Battle room not found"); if (!battle.hostId.equals(req.user!.id)) throw ApiError.forbidden("Only the host can start this battle"); if (battle.players.length !== 2) throw ApiError.badRequest("Waiting for an opponent to join"); if (battle.status === "waiting") { battle.status = "active"; battle.startedAt = new Date(); await battle.save(); } return res.success(200, "Battle started", await stateFor(battle, req.user!.id)); } catch (error) { next(error); } }
export async function submitAnswer(req: Request, res: Response, next: NextFunction) { try { const input = answerSchema.parse(req.body); const battle = await Battle.findOne({ roomCode: String(req.params.roomCode).toUpperCase() }); if (!battle || battle.status !== "active") throw ApiError.badRequest("Battle is not active"); const player = battle.players.find((candidate) => candidate.userId.equals(req.user!.id)); if (!player) throw ApiError.forbidden(); if (player.answers.some((answer) => answer.questionId === input.questionId)) throw ApiError.badRequest("That answer has already been submitted"); const question = battle.questions.find((candidate) => candidate.questionId === input.questionId); if (!question) throw ApiError.badRequest("Unknown question"); const isCorrect = input.answer.trim() === question.correctAnswer; player.answers.push({ questionId: question.questionId, answer: input.answer.trim(), isCorrect, timeTaken: input.timeTaken, submittedAt: new Date() }); if (isCorrect) player.score += question.xpValue; if (battle.players.every((candidate) => candidate.answers.length >= battle.questions.length)) { battle.status = "finished"; battle.endedAt = new Date(); const [first, second] = battle.players; battle.winnerId = first.score === second.score ? null : (first.score > second.score ? first.userId : second.userId); } await battle.save(); return res.success(200, "Answer recorded", { isCorrect, xpEarned: 0, currentScore: player.score, finished: battle.status === "finished" }); } catch (error) { next(error); } }
export async function forfeitBattle(req: Request, res: Response, next: NextFunction) { try { const battle = await Battle.findOne({ roomCode: String(req.params.roomCode).toUpperCase() }); if (!battle || !hasPlayer(battle, req.user!.id)) throw ApiError.notFound("Battle room not found"); const opponent = battle.players.find((player) => !player.userId.equals(req.user!.id)); battle.status = "finished"; battle.endedAt = new Date(); battle.winnerId = opponent?.userId ?? null; await battle.save(); return res.success(200, "Battle forfeited", { outcome: opponent ? "loss" : "draw" }); } catch (error) { next(error); } }
