import { useEffect, useState } from 'react'
import { Flame, Github, LoaderCircle, Swords, Trophy } from 'lucide-react'
import { Link } from 'react-router-dom'
import type { IGitHubStats } from '../types'
import { userService } from '../services/user.service'
import { useAuth } from '../hooks/useAuth'

export default function Dashboard() {
  const { user } = useAuth()
  const [stats, setStats] = useState<IGitHubStats | null>(null)
  const [syncing, setSyncing] = useState(false)
  const [error, setError] = useState<string | null>(null)
  useEffect(() => { userService.getMyGithubStats().then((data) => setStats(data.githubStats)).catch(() => undefined) }, [])
  async function sync() { setSyncing(true); setError(null); try { const data = await userService.syncGithub(); setStats(data.githubStats) } catch (err) { setError(err instanceof Error ? err.message : 'Unable to sync GitHub.') } finally { setSyncing(false) } }
  const cards = [[String(stats?.totalRepos ?? '—'),'repositories',Github],[String(stats?.totalCommits ?? '—'),'recent pushes',Swords],[stats ? `${stats.longestStreak} days` : '—','longest streak',Flame],[user?.rank ? `#${user.rank}` : '—','global rank',Trophy]] as const
  return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold text-primary">YOUR PROOF OF SKILL</p><h1 className="mt-1 font-display text-4xl font-bold">{user ? `Welcome, ${user.userName}.` : 'Your developer command center.'}</h1><p className="mt-2 text-textMuted">GitHub facts are collected and cached by DevArena—not supplied by your browser.</p></div><button onClick={() => void sync()} disabled={syncing} className="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-3 font-bold text-background disabled:opacity-60">{syncing ? <LoaderCircle className="animate-spin" size={17}/> : <Github size={17}/>} {syncing ? 'Analysing GitHub…' : stats ? 'Refresh GitHub' : 'Analyse GitHub'}</button></div>{error && <div className="mt-5 rounded-xl border border-danger/40 bg-danger/10 p-4 text-sm text-red-200">{error}</div>}<div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([value,label,Icon])=><div key={label} className="rounded-2xl border border-border bg-surface p-5"><Icon size={19} className="text-primary"/><p className="mt-5 text-3xl font-bold">{value}</p><p className="mt-1 text-sm text-textMuted">{label}</p></div>)}</div>{stats ? <div className="mt-6 grid gap-6 lg:grid-cols-[1.35fr_.65fr]"><section className="rounded-2xl border border-border bg-surface p-6"><p className="font-bold">GitHub intelligence</p><p className="mt-1 text-sm text-textMuted">Cached data from your connected GitHub account.</p><div className="mt-6 rounded-2xl bg-gradient-to-br from-secondary/30 to-primary/15 p-6"><p className="text-sm font-bold text-primary">TOP LANGUAGE · {stats.topLanguage ?? 'Still calculating'}</p><h2 className="mt-2 font-display text-3xl font-bold">{Object.keys(stats.languages).length} languages across {stats.publicRepos} public repositories.</h2><p className="mt-3 text-textMuted">{stats.stars} stars · {stats.forks} forks · {stats.followers} followers</p></div></section><section className="rounded-2xl border border-border bg-surface p-6"><p className="font-bold">Continue your story</p><p className="mt-2 text-sm text-textMuted">Developer DNA is the next server-side step built from these stored statistics.</p><Link to="/dna" className="mt-6 block rounded-xl border border-primary/40 py-2.5 text-center text-sm font-bold text-primary">View Developer DNA</Link></section></div> : <div className="mt-6 rounded-2xl border border-dashed border-border bg-surface p-8 text-center"><p className="font-bold">Ready to read your GitHub story?</p><p className="mt-2 text-sm text-textMuted">Run analysis once. DevArena caches the result and refreshes it at a controlled interval.</p></div>}</div>
}
